/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsplitpane;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Invitado_PC07
 */
public class MouseClick extends javax.swing.JFrame {

    /**
     * Creates new form MouseClick
     */
    public MouseClick() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuemergente = new javax.swing.JPopupMenu();
        jMenuItemRojo = new javax.swing.JMenuItem();
        jMenuItemVerde = new javax.swing.JMenuItem();
        jMenuItemAzul = new javax.swing.JMenuItem();

        jMenuItemRojo.setText("Rojo");
        jMenuItemRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRojoActionPerformed(evt);
            }
        });
        jPopupMenuemergente.add(jMenuItemRojo);

        jMenuItemVerde.setText("Verde");
        jMenuItemVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerdeActionPerformed(evt);
            }
        });
        jPopupMenuemergente.add(jMenuItemVerde);

        jMenuItemAzul.setText("Azul");
        jMenuItemAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAzulActionPerformed(evt);
            }
        });
        jPopupMenuemergente.add(jMenuItemAzul);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
//        if (evt.getButton() == 1) {
//            JOptionPane.showMessageDialog(null, "Pulso el izquierdo");
//        } else if (evt.getButton() == 2) {
//            JOptionPane.showMessageDialog(null, "Pulso el central");
//        } else if (evt.getButton() == 3) {
//            JOptionPane.showMessageDialog(null, "Pulso el derecho");
//        }

jPopupMenuemergente.show(this, evt.getX(), evt.getY());

    }//GEN-LAST:event_formMouseClicked

    private void jMenuItemRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRojoActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.RED);

    }//GEN-LAST:event_jMenuItemRojoActionPerformed

    private void jMenuItemVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerdeActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.GREEN);
    }//GEN-LAST:event_jMenuItemVerdeActionPerformed

    private void jMenuItemAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAzulActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.BLUE);
    }//GEN-LAST:event_jMenuItemAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MouseClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MouseClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MouseClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MouseClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseClick().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItemAzul;
    private javax.swing.JMenuItem jMenuItemRojo;
    private javax.swing.JMenuItem jMenuItemVerde;
    private javax.swing.JPopupMenu jPopupMenuemergente;
    // End of variables declaration//GEN-END:variables
}
